### PR TITLE
update project with new API path add vendor

### PR DESCRIPTION
**Pull request by msherif1234**

### CODE REVIEW

**Comment by astoycos** [comment]
@msherif1234, Just out of curiosity what's our main reason for downloading/tracking vendor here? IMO It just adds a bunch more diff to sort through whenever things are changed + adds 1.3 million lines of code for us to track 😮‍💨 

Is this just how it's done across OCP? It's really just weighing the pros and cons https://github.com/golang/dep/blob/master/docs/FAQ.md#should-i-commit-my-vendor-directory

**Comment by msherif1234** [comment]
OCP use vendor and `-mod vendor ` to build the operator binary for almost all operators I worked with :(, I haven't change the go build yet I can do that in this PR ?

**Comment by astoycos** [comment]
> OCP use vendor and -mod vendor  to build the operator binary for almost all operators I worked with :(, I haven't change the go build yet I can do that in this PR ?

If that's just "how it's done" in OCP yeah I'm alright with it 👍 Thanks!

**Comment by msherif1234** [comment]
updated all the make to build using vendor packages

**Review by astoycos — APPROVED** [review]
LGTM 

Thanks @msherif1234

**Pull request merged**
